package ejemplohiber;
// Generated 03-nov-2021 15:37:40 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer id;
     private Departamentos departamentos;
     private Empleados empleados;
     private String apellido;
     private String cargo;
     private Date fechaAlta;
     private Double salario;
     private Double comision;
     private Set empleadoses = new HashSet(0);

    public Empleados() {
    }

    public Empleados(Departamentos departamentos, Empleados empleados, String apellido, String cargo, Date fechaAlta, Double salario, Double comision, Set empleadoses) {
       this.departamentos = departamentos;
       this.empleados = empleados;
       this.apellido = apellido;
       this.cargo = cargo;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.comision = comision;
       this.empleadoses = empleadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public Empleados getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Empleados empleados) {
        this.empleados = empleados;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Double getComision() {
        return this.comision;
    }
    
    public void setComision(Double comision) {
        this.comision = comision;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }




}


